name: gold_purchase_app
description: A new Flutter project for a jewelry app with multilingual support.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  jwt_decoder: ^2.0.1
  share_plus: ^7.2.1
  table_calendar: ^3.0.9
  get: ^4.6.6
  razorpay_flutter: ^1.3.5
  animated_widgets: ^1.1.0
  animate_do: ^3.0.2
  provider: ^6.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  lottie: ^3.1.0 
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  flutter_animate: ^4.3.0

  fl_chart: ^0.66.0  # âœ… This must be here!
  pin_code_fields: ^8.0.1


  # ðŸŒ™ Cupertino icons
  cupertino_icons: ^1.0.8

  # ðŸŒ Localization support
  flutter_localizations:
    sdk: flutter

  # ðŸŒ Internationalization for strings
  intl: ^0.20.2

  # ðŸ§© Swiper for image carousels
  flutter_swiper_null_safety: ^1.0.2

  # ðŸ§± Optional: Icon packs if used
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  url_launcher: ^6.1.10   
  font_awesome_flutter: ^10.4.0

  flutter_lints: ^5.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"



flutter:
  uses-material-design: true
  assets:
    - assets/images/banner.jpg
    - assets/images/goldimg.png
    - assets/images/banner1.jpg
    - assets/images/goldbanner.jpg
    - assets/images/goldcoin.jpeg
    - assets/animations/silverCoin.json
    - assets/lottie/coin_silver.json
    - assets/animations/Levelupsilver.json
    - assets/animations/goldanimation.json
    - assets/animations/Payment.json
    - assets/animations/lock.json
    - assets/animations/lock1.json
    - assets/animations/lock2.json
    - assets/animations/lock3.json
    - assets/images/appicon.png
    - assets/.env

